name: deploy site

on:
    push:
        branches:
            - docs

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: check out
                uses: actions/checkout@v4

            -   name: set up bun
                uses: oven-sh/setup-bun@v2

            -   name: install
                working-directory: site
                run: bun install --frozen-lockfile

            -   name: build
                working-directory: site
                run: bun run build

            -   name: deploy to Cloudflare Pages
                working-directory: site
                env:
                    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                run: bunx wrangler pages deploy --branch=master
