name: "Release"
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message,'build:')"
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Build plugin
        run: |
          bun install
          bun run build

      - name: "Get the tag"
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.get_tag.outputs.tag }}

          gh release create "$tag" \
          --title="$tag" \
          --draft \
            main.js manifest.json styles.css LICENSE README.md

      



